### ISSUE TITLE
Getting the following error when I install in 2.79

### ISSUE THREAD

**Issue by GeminiSquishGames** [opparco/io_scene_tso_tmo#1]
After installing the zip file from user menu, I click on the check box to mark it for use and I get this:

> 
> Modules Installed (io_scene_tso_tmo-master) from 'C:\\Users\\Ben\\Desktop\\io_scene_tso_tmo-master.zip' into 'C:\\Users\\Ben\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons'
> Traceback (most recent call last):
>   File "C:\graphics\Blender\2.79\scripts\modules\addon_utils.py", line 331, in enable
>     mod = __import__(module_name)
>   File "C:\Users\Ben\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene_tso_tmo-master\__init__.py", line 6, in <module>
>     from io_scene_tso_tmo import tso_import_op, tmo_import_op, tso_export_op
> ImportError: No module named 'io_scene_tso_tmo'
>

**Comment by GenesisAria** [comment]
remove "-develop" from folder name and it works.
